import './home.js';
import './quran.js';
import './dailyVerse.js';
import './hadith.js';
import './prophetsStories.js';
import './dua.js';
import './reciters.js';
import './prayerTimes.js';
import './tasbeeh.js';
import './prayerTracker.js';
import './halalHaram.js';
import './repentance.js';
import './comparativeReligion.js';
import './quotes.js';
import './nasheed.js';
import './books.js';
import './progress.js';
import './settings.js';
import './about.js';
import './utils.js';

document.getElementById('app').innerText = 'Welcome to The Journey to Janneh PWA';
console.log('All modules loaded.');
